name: "Generate Arch Repo database and upload"
description: "Upload generated Arch Repo database to object storage (S3 compatible)"
inputs:
  S3_ENDPOINT_URL:
    description: "S3 endpoint URL (optional, for S3-compatible services)"
    required: false
  S3_ACCESS_KEY_ID:
    description: "S3 access key ID"
    required: true
  S3_SECRET_ACCESS_KEY:
    description: "S3 secret access key"
    required: true
  S3_BUCKET_NAME:
    description: "S3 bucket name"
    required: true
  S3_REGION:
    description: "S3 region (default: us-east-1)"
    required: false
    default: "us-east-1"
  dest_path:
    description: "Destination path in the bucket"
    required: true
  repo_name:
    description: "Repository name"
    required: true
  local_path:
    description: "Local path containing packages"
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"

  env:
    S3_ENDPOINT_URL: ${{ inputs.S3_ENDPOINT_URL }}
    S3_ACCESS_KEY_ID: ${{ inputs.S3_ACCESS_KEY_ID }}
    S3_SECRET_ACCESS_KEY: ${{ inputs.S3_SECRET_ACCESS_KEY }}
    S3_BUCKET_NAME: ${{ inputs.S3_BUCKET_NAME }}
    S3_REGION: ${{ inputs.S3_REGION }}
    dest_path: ${{ inputs.dest_path }}
    repo_name: ${{ inputs.repo_name }}
    local_path: ${{ inputs.local_path }}
